### ISSUE TITLE
Implementirati klasu Put

### ISSUE THREAD

**Issue by GojakMilica** [pfe-rs/zr-s-2024-simulator-saobracaja#6]
klasa put treba da sadrzi broj traka

**Comment by najkela** [comment]
> klasa put treba da sadrzi broj traka

Mi smo mislili da broj traka implementiramo preko broja puteva, slično kao što smo i dvosmernu ulicu predstavili preko 2 puta umesto preko jednog koji je dvosmeran. Na primer ako je između rasrsnice 1 i 2 ulica sa dve trake napravićemo 2 puta koji idu od 1 do 2.

**Comment by GojakMilica** [comment]
> > klasa put treba da sadrzi broj traka
> 
> Mi smo mislili da broj traka implementiramo preko broja puteva, slično kao što smo i dvosmernu ulicu predstavili preko 2 puta umesto preko jednog koji je dvosmeran. Na primer ako je između rasrsnice 1 i 2 ulica sa dve trake napravićemo 2 puta koji idu od 1 do 2.

Aha, ok je, to je onda na vama. Ja smatram da je to samo atribut puta koji ce posle da diktira koliki je protok, npr autoput ima barem 3 trake ili kako vec
